# Generated by Django 2.2 on 2019-04-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('text', models.TextField(verbose_name='Описание отеля')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('capacity', models.IntegerField(verbose_name='Вметимость')),
                ('rooms_type', models.CharField(max_length=200, verbose_name='Типы номеров')),
                ('accommodation', models.CharField(max_length=200, verbose_name='Удобства')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('keywords', models.CharField(max_length=50, verbose_name='Клчевые слова')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
    ]
