# Generated by Django 2.2 on 2019-04-22 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivago', '0004_auto_20190421_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='period',
            field=models.CharField(max_length=100, null=True, verbose_name='Период проживания'),
        ),
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
