# Generated by Django 2.2 on 2019-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivago', '0005_auto_20190422_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='period',
            field=models.DateField(null=True, verbose_name='Период проживания'),
        ),
    ]
