# Generated by Django 2.2 on 2019-06-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivago', '0006_auto_20190422_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomnum', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Модерация')),
                ('telephone', models.BigIntegerField()),
                ('floor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип номера')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='Scedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=20, verbose_name='День недели')),
                ('floor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passmun', models.CharField(max_length=100, verbose_name='Номер паспорта')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('fathersname', models.CharField(max_length=100, verbose_name='Отчество')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('settlement_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата въезда')),
                ('departure_date', models.DateTimeField(verbose_name='Дата отезда')),
                ('roomnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivago.Room', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('fathersname', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.AddField(
            model_name='scedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivago.Worker', verbose_name='Работник'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivago.RoomType', verbose_name='Тип номера'),
        ),
    ]
