# Generated by Django 2.2 on 2019-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivago', '0007_auto_20190619_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomnum',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
