# Generated by Django 2.2 on 2019-06-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivago', '0008_auto_20190619_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Свободен'),
        ),
    ]
