# Generated by Django 2.2 on 2019-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivago', '0009_auto_20190619_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='settlement_date',
            field=models.DateTimeField(verbose_name='Дата въезда'),
        ),
    ]
