# Generated by Django 2.2 on 2019-06-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivago', '0010_auto_20190619_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateTimeField(verbose_name='Дата въезда')),
            ],
            options={
                'verbose_name': 'Заселение',
                'verbose_name_plural': 'Заселения',
            },
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='roomnum',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='settlement_date',
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(verbose_name='Дата отезда')),
                ('lastname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivago.Checkin')),
            ],
            options={
                'verbose_name': 'Выселение',
                'verbose_name_plural': 'Выселение',
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='lastname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivago.Visitor'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='roomnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivago.Room', verbose_name='Тип номера'),
        ),
    ]
